### PR TITLE
Bugfix: Fix out of bounds error for getting z notes

### PR DESCRIPTION
**Pull request by danagilliann**
Fixes this out of bounds error by reducing the index number by 1 when
the index produced by searchsorted is equal to the last index of
t_instruments

### CODE REVIEW

**Comment by danagilliann** [comment]
@googlebot Signed!

**Comment by danagilliann** [comment]
@googlebot I signed it!

**Comment by jesseengel** [comment]
Looks like it needs to be from this email address: 
danagilliann@users.noreply.github.com

**Comment by danagilliann** [comment]
@googlebot i signed it!

**Pull request merged**
