### PR TITLE
Fix is sequence

### PR DESCRIPTION
**Pull request by eraoul**
_is_sequence and _unpacked_state disappeared in TF 0.10; I had to update to use tensorflow.python.util.nest instead. I assume this change would break users with TF 0.9, however.

### CODE REVIEW

**Comment by adarob** [comment]
Yes, this is unfortunate since it will break 0.9 users. Can you also include an update to the installation instructions to say that 0.10 or greater is required?

**Comment by eraoul** [comment]
Sure thing -- done.

**Comment by adarob** [comment]
Thanks. I'm going to discuss with the team how best to roll this out since it is not backwards compatible.

**Comment by eraoul** [comment]
SGTM. Maybe it's reasonable to add a check to see if those functions exist
to preserve compatibility for a version or two..

**Pull request merged**
