### PR TITLE
Fixed a bad line-break

### PR DESCRIPTION
**Pull request by orta**
Hey - awesome blog post - really interesting work! 
Spotted a markdown bug in your blog post.  the `()` have to directly follow `[]` - the line break means the link isn't created.

### CODE REVIEW

**Comment by orta** [comment]
I signed it!

**Comment by fredbertsch** [comment]
Thanks so much for the fix.

**Comment by douglaseck** [comment]
Thanks for the fix! I may have already checked in the same fix, but it's
much appreciated (not sure what order things went in).

**Comment by orta** [comment]
No worries, I can close it 👍  there's merge conflicts

**Pull request closed without merging**
