### PR TITLE
Improve error reporting during MIDI conversion.

### PR DESCRIPTION
**Pull request by cghawthorne**
Always raise exceptions, push exception-handling logic to callers rather
than having chains of continue_on_exception args.

Log filenames of midi files with conversion errors.

Set default log level to INFO in convert_midi_dir_to_note_sequences.

### CODE REVIEW

**Comment by cghawthorne** [comment]
This should help debug some of the issues in #104.

**Comment by danabo** [comment]
LGTM

**Comment by hpssjellis** [comment]
@cghawthorne where are the new log files being saved? I have noticed the output information telling me how many midi files have been processed is not showing anymore.

**Comment by cghawthorne** [comment]
@hpssjellis it should just show up on stdout:

```
$ bazel run //magenta/scripts:convert_midi_dir_to_note_sequences -- --midi_dir=$MIDI_DIRECTORY --output_file=$SEQUENCES_TFRECORD --recursive
...
INFO:tensorflow:Converted 2 MIDI files in '/tmp/midis/'.
INFO:tensorflow:Coult not parse 3 MIDI files.
INFO:tensorflow:Wrote 2 NoteSequence protos to '/tmp/notesequences.tfrecord'

```

**Pull request merged**
