### PR TITLE
Fix typo in MusicVAE README.md

### PR DESCRIPTION
**Pull request by Elvenson**
Fix typo in MusicVAE README.md. Specifically, inerpolate to interpolate and ceratin to certain.

### CODE REVIEW

**Comment by adarob** [comment]
Thanks! Please sign the CLA and we can pull your change.

**Comment by Elvenson** [comment]
Just signed it!

**Comment by adarob** [comment]
@googlebot He signed it!

**Comment by Elvenson** [comment]
@googlebot I fixed it.

**Pull request merged**
