### PR TITLE
Fix quantization error during generation resulting in crashes.

### PR DESCRIPTION
**Pull request by adarob**

### CODE REVIEW

**Comment by adarob** [comment]
I didn't mean to do it in this PR, but I am about to push a new version, so might as well.

**Comment by zhou13** [comment]
Will this PR make quantization less accurate?  It seems that it reduces the duration of all the notes by one step.

**Comment by iansimon** [comment]
This shouldn't affect the duration of individual notes, but the start/end times of generated sequences.  Are you observing any difference in note durations?

**Comment by zhou13** [comment]
Oh my bad.

**Pull request merged**
