### PR TITLE
Use six for Py2 and Py3 compatible urlretrieve and BytesIO (Continues PR #1345)

### PR DESCRIPTION
**Pull request by vaipatel**
Just finishing up the desired changes for #1345 which should make sketch_rnn_train.py work for both Python 2 and 3.

### CODE REVIEW

**Comment by vaipatel** [comment]
I signed it!

**Comment by vaipatel** [comment]
I signed it again! (hopefully it's the right email this time!)

**Comment by cghawthorne** [comment]
Hey @vaipatel it looks like the CLA bot still isn't happy. You might have to edit your commit (possibly with some form of rebase/squash) to make the author email address correct.

**Comment by vaipatel** [comment]
Hey @cghawthorne, you're right, I just realized I hadn't configured my email in first the commit. I pushed another commit after configuring the email but that doesn't work either.

I haven't really done an interactive rebase before, I'm going to follow the steps [here](https://stackoverflow.com/a/3042512) to see if I can amend the author for my first commit.

**Comment by vaipatel** [comment]
Commenting again for CLA bot

**Pull request merged**
