### PR TITLE
typo

### PR DESCRIPTION
**Pull request by unboundmusic**

### CODE REVIEW

**Comment by adarob** [comment]
Thanks @unboundmusic! Please let us know when you sign the CLA so we can merge in your fix.

**Comment by adarob** [comment]
@unboundmusic, please sign the CLA or I will need to create a separate PR to get this fix in. Thanks!

**Comment by unboundmusic** [comment]
I signed it. Maybe the email address is not matching up with my gmail address. I put in my github username in the CLA

**Comment by adarob** [comment]
Thanks!

**Pull request merged**
