### PR TITLE
rename nonexisting filename. clarify explanation.

### PR DESCRIPTION
**Pull request by vug**
convert_sequences_to_melodies.py -> basic_rnn_create_dataset.py

### CODE REVIEW

**Comment by vug** [comment]
I signed it!

**Comment by danabo** [comment]
Thank you for updating this.

**Comment by danabo** [comment]
Resolve conflicts and I'll merge your PR. convert_sequences_to_melodies.py appears twice in the readme, can you update the name in both places? Thank you :)

**Comment by vug** [comment]
Oh, I missed that one. Updated other name too. ^_^

**Comment by vug** [comment]
@danabo Sorry, I am a Git/OpenSource newbie. I resolved the conflicts but when I pushed the changes with SourceTree my email address was missing. :-( That's why it is not passing the CLA. Should I close this PR and open a new one?

**Comment by fredbertsch** [comment]
Yeah, we're going to need an account that can sign the CLA. Can you recreate the PR?

**Comment by vug** [comment]
@fredbertsch Sure! Recreated this at PR #76 with correctly signed CLA. Feel free to close this one.

**Pull request closed without merging**
