### PR TITLE
Simplifying binary counters + making them consistent between models

### PR DESCRIPTION
**Pull request by eraoul**
Also noticed a missing "len(melody)-1" in the attention model.

### CODE REVIEW

**Comment by cghawthorne** [comment]
@elliotwaite can you take a look at this?

**Comment by eraoul** [comment]
I signed the CLA.

**Comment by elliotwaite** [comment]
Actually, I think it should be "n = len(melody)" for both. It shifts the binary clock forward one to give the correct signal for what the next note should be, instead of signalling what the time position of the last note was. For example, the bar binary counter should be -1.0 for the first 15 inputs, but change to 1.0 for the 16th input, so that it will signal the start of a new bar for generating the 17th step.

For example, instead of n = len(melody) - 1:
1: [0, 0, 0, 0, 0]
2: [1, 0, 0, 0, 0]
3: [0, 1, 0, 0, 0]
4: [1, 1, 0, 0, 0]
5: [0, 0, 1, 0, 0]
6: [1, 0, 1, 0, 0]
7: [0, 1, 1, 0, 0]
8: [1, 1, 1, 0, 0]
9: [0, 0, 0, 1, 0]
10: [1, 0, 0, 1, 0]
11: [0, 1, 0, 1, 0]
12: [1, 1, 0, 1, 0]
13: [0, 0, 1, 1, 0]
14: [1, 0, 1, 1, 0]
15: [0, 1, 1, 1, 0]
16: [1, 1, 1, 1, 0]
17: [0, 0, 0, 0, 1]
18: [1, 0, 0, 0, 1]
19: [0, 1, 0, 0, 1]
20: [1, 1, 0, 0, 1]
21: [0, 0, 1, 0, 1]
22: [1, 0, 1, 0, 1]
23: [0, 1, 1, 0, 1]
24: [1, 1, 1, 0, 1]
25: [0, 0, 0, 1, 1]
26: [1, 0, 0, 1, 1]
27: [0, 1, 0, 1, 1]
28: [1, 1, 0, 1, 1]
29: [0, 0, 1, 1, 1]
30: [1, 0, 1, 1, 1]
31: [0, 1, 1, 1, 1]
32: [1, 1, 1, 1, 1]

It should be n = len(melody), since the input is for predicting the next note:
1: [1, 0, 0, 0, 0]
2: [0, 1, 0, 0, 0]
3: [1, 1, 0, 0, 0]
4: [0, 0, 1, 0, 0]
5: [1, 0, 1, 0, 0]
6: [0, 1, 1, 0, 0]
7: [1, 1, 1, 0, 0]
8: [0, 0, 0, 1, 0]
9: [1, 0, 0, 1, 0]
10: [0, 1, 0, 1, 0]
11: [1, 1, 0, 1, 0]
12: [0, 0, 1, 1, 0]
13: [1, 0, 1, 1, 0]
14: [0, 1, 1, 1, 0]
15: [1, 1, 1, 1, 0]
16: [0, 0, 0, 0, 1]
17: [1, 0, 0, 0, 1]
18: [0, 1, 0, 0, 1]
19: [1, 1, 0, 0, 1]
20: [0, 0, 1, 0, 1]
21: [1, 0, 1, 0, 1]
22: [0, 1, 1, 0, 1]
23: [1, 1, 1, 0, 1]
24: [0, 0, 0, 1, 1]
25: [1, 0, 0, 1, 1]
26: [0, 1, 0, 1, 1]
27: [1, 1, 0, 1, 1]
28: [0, 0, 1, 1, 1]
29: [1, 0, 1, 1, 1]
30: [0, 1, 1, 1, 1]
31: [1, 1, 1, 1, 1]
32: [0, 0, 0, 0, 0]

It's counter intuitive since you're feeding in information about the previous note, but the time clock is the signal for the next note, but I think it's the right strategy. Thanks for finding that inconsistency between lookback_rnn and attention_rnn.

Other than that, the change looks good to me.

**Comment by adarob** [comment]
LGTM, thanks!

**Comment by eraoul** [comment]
Makes sense -- I could see an argument for doing it either way, but yes, I've modified to point at the next note.

An aside: I think the previous (and current) code has "-1" and "1" reversed from what one would expect (i.e., "result = 1 if ....... %2 else -1" seems backwards from what you described above). But it doesn't really matter as long as all the examples are consistent :) Should we swap them or leave it alone?

**Pull request merged**
