### PR TITLE
parse MusicXML chord symbols and store as NoteSequence text annotations

### PR DESCRIPTION
**Pull request by iansimon**

### CODE REVIEW

**Comment by iansimon** [comment]
@jsawruk you may be interested in this.

**Comment by iansimon** [comment]
@jsawruk is your thumbs-up on my previous comment a confirmation that you are in fact interested, or did you try parsing chord symbols and it seemed to work?

**Comment by jsawruk** [comment]
@iansimon: Both! I tested and had no problem with any of the MusicXML files I used (about 150 PVG arrangements).

**Comment by iansimon** [comment]
Awesome!  Thanks for checking :)

**Pull request merged**
