### PR TITLE
wrote review of the rnn rbm

### PR DESCRIPTION
**Pull request by dshieble**

### CODE REVIEW

**Comment by dshieble** [comment]
I signed it!

**Comment by dshieble** [comment]
This pull request includes the review of [Boulanger-Lewandowski 2012](http://www-etud.iro.umontreal.ca/~boulanni/ICML2012.pdf), with a focus on the RNN-RBM architecture and its applications to generating polyphonic music. I'm looking forward to hearing feedback on the review. Thank you.

**Comment by cinjon** [comment]
Thanks Dan! I'll look at this this weekend and get back to you with any comments and edits. Much appreciated.

**Comment by dshieble** [comment]
Great!

**Comment by cinjon** [comment]
For posterity in the PR, a heads up that we're editing this offline.

**Comment by cinjon** [comment]
Edits offline.

**Comment by cinjon** [comment]
LGTM. Thanks Dan!

**Pull request merged**
