### PR TITLE
Small typo in exception

### PR DESCRIPTION
**Pull request by lucianthorr**
I hit this exception on my first time running and it appears to have raised an error.

### CODE REVIEW

**Comment by lucianthorr** [comment]
I signed it!

**Comment by bryongloden** [comment]
Greetings @lucianthorr! I see this issue was closed an hour ago. Was your code merged (accepted) somewhere else?

**Comment by lucianthorr** [comment]
I realized that what I thought was an error was really a discrepancy
between Python 2 and Python 3.

**Comment by fredbertsch** [comment]
We'd like to have Magenta work with either Python 2.7+ or 3. Internally at
Google, we tend to use 2.7 unless we deliberately try 3. Our style guide
<https://google.github.io/styleguide/pyguide.html#Exceptions> even requests
the as syntax.

I'd be happy to accept your pull request if you send it again.

-Fred (another Magenta engineer)

**Comment by lucianthorr** [comment]
Python 2 vs Python 3 syntax

**Comment by lucianthorr** [comment]
Fred, thanks for the response and this style guide is great help.  I wasn't
sure if small edits like that should be suggested via pull request or
opening an issue.
I'm happy to help however I can and look forward to playing more with
Magenta soon.
-Jason

**Comment by fredbertsch** [comment]
Thanks for the fix!

**Comment by subhadipna** [comment]
I signed it!

On Wed, Jun 22, 2016 at 7:30 AM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/magenta/pull/61#issuecomment-227623100>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALMidchhd74AzCueSJeC--9tButZbRuIks5qOJcngaJpZM4I7VoM>
> .
>



-- 
Regards
Subhadip Nath
+918861019940

**Comment by fredbertsch** [comment]
Good question, @lucianthorr. We're happy to take either one, but we're currently able to move faster on PRs. We're still figuring out how to tie our internal code to this repo, and we don't have a complete story about issues yet. Expect to hear more as we learn how to do this smoothly.

**Comment by bryongloden** [comment]
Greetings @lucianthorr. How are you? I didn't remember if I signed too.

**Pull request merged**
